correction of issue on tubular-react "Print does not print all rows #901"
unosquare/tubular-react-common pull request #358
Opened 2020-12-17 16:56 UTC by ccastello

only useTubular.js is affected.
I change -1 to 100000 to say that's all rows

2021-03-01 17:07 UTC, geoperez approved these changes

2021-03-02 17:02 UTC, geoperez commented
Can you fix the conflicting files? Thank you

2021-03-03 14:37 UTC, kadosh requested changes
Hey @ccastello,
Thanks for your interest in tubular and the PR you're doing. I have a couple of comments for this PR.

2021-03-03 14:37 UTC, kadosh commented on src/helpers.ts
> +import camelcase from 'camelcase'
This is totally an implementation-specific requirement. We should not add camelcase package just to format the exported file. That can be done by the implementation.

2021-03-03 14:37 UTC, kadosh commented on src/helpers.ts
> +function exportFile(gridResult: [], columns: ColumnModel[], gridName: string): void {
I really like this. Just one thing: can you put a default value to it? gridName = "data". This is to avoid breaking changes.

2021-03-03 14:37 UTC, kadosh commented on src/useTubular.ts
> +                ? (await getAllRecords()(new GridRequest(tbState.columns, 1000000, 0, tbState.searchText))).payload
This is not needed. We have addressed this issue at https://github.com/unosquare/tubular-common/pull/347/files#diff-d0a0ca5370b12b88e923d3279fd11385944530ff630be9fa2637d762d0ef24fbR79.

2021-03-03 14:37 UTC, kadosh commented on package.json
> +    "version": "3.1.1",
You don't need to modify anything here, CI will take care of it.

2021-03-04 11:18 UTC, ccastello commented
It wasn't a good job. I recreated a new pull request.

2021-03-04 11:19 UTC, closed without merging